#!/usr/bin/env bash
# PreToolUse guard. Blocks edits to machine-generated / committed-state files
# that the daily pipeline owns. Hand-editing these either corrupts dedupe
# state or gets silently overwritten by the next run.
#
# Reads the hook payload on stdin, extracts the target path, and exits 2
# (with a message on stderr) to deny the edit. Any non-generated path passes
# through untouched (exit 0).

set -euo pipefail

payload="$(cat)"
path="$(printf '%s' "$payload" | jq -r '.tool_input.file_path // empty')"

# No path in payload (e.g. a tool we do not care about) -> allow.
[ -z "$path" ] && exit 0

# Compare on the repo-relative path so absolute or relative inputs both match.
rel="${path#"${CLAUDE_PROJECT_DIR:-$PWD}/"}"

case "$rel" in
  data/*.db | \
  _posts/*-cryptoccino.md | \
  assets/cards/* | \
  assets/sparklines/* | \
  assets/data/prices.json | \
  _site/*)
    echo "Blocked: '$rel' is generated by the daily pipeline (run.py) and committed back to main." >&2
    echo "Edit the source instead — pipeline/ code, config/feeds.yaml, prompts/brief_system.md, or _layouts/." >&2
    echo "If you genuinely need to change it by hand, do it outside Claude or remove this guard in .claude/settings.json." >&2
    exit 2
    ;;
esac

exit 0
